name = "realfiction-platform"
main = ".open-next/worker.js"
compatibility_date = "2026-05-20"
compatibility_flags = ["nodejs_compat", "global_fetch_strictly_public"]

[build]
command = "npm run build:cloudflare"

[assets]
directory = ".open-next/assets"
binding = "ASSETS"

[vars]
NEXT_PUBLIC_SITE_URL = "https://realfiction.live"
NEXT_PUBLIC_MINECRAFT_SERVER = "realfiction.live"
NEXT_PUBLIC_BEDROCK_SERVER = "bedrock.realfiction.live"
